Server: Extract raw api to be implemented in Project1 into raw_api.go
talent-plan/tinykv pull request #285
Opened 2021-08-24 07:58 UTC by pupillord

### What problem does this PR solve?
Rearrange code of project1

### What is changed
Extract raw api to be implemented in Project1 into raw_api.go

Issue : [Rearrange code of project1 · Issue #283 · tidb-incubator/tinykv (github.com)](https://github.com/tidb-incubator/tinykv/issues/283)

2021-08-24 07:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tidb-incubator/tinykv?pullRequest=285) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tidb-incubator/tinykv?pullRequest=285) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tidb-incubator/tinykv?pullRequest=285) it.</sub>

2021-08-24 11:57 UTC, ngaut approved these changes
LGTM

2021-08-24 23:54 UTC, tisonkun requested changes
Thanks for your contribution @pupillord ! Comments inline.

Also it would be better if you can elaborate more on functions in `raw_api.go`

2021-08-24 23:54 UTC, tisonkun commented on kv/server/server.go
> +// Implement raw api in raw_api.go
We don't need this line then.

We should update the document and mention "related file" as described in #275 .

2021-08-24 23:54 UTC, tisonkun commented on kv/server/raw_api.go
> +}
Add a new line or just run `go fmt`.

2021-08-25 09:23 UTC, tisonkun approved these changes
LGTM. Thanks for your contribution!

Merging...

2021-08-25 09:24 UTC, merged