fix(raft): LogTerm exceed Term
talent-plan/tinykv pull request #323
Opened 2021-11-26 03:41 UTC by oocococo

LogTerm should always be smaller than Term in AppendMsg

fix #322

2021-11-26 03:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tidb-incubator/tinykv?pullRequest=323) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tidb-incubator/tinykv?pullRequest=323) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tidb-incubator/tinykv?pullRequest=323) it.</sub>

2021-11-26 06:32 UTC, NingLin-P approved these changes
LGTM, thanks!

2021-11-26 07:25 UTC, Connor1996 requested changes
I think it's intentional for the test, please check again @NingLin-P

2021-11-26 09:56 UTC, NingLin-P commented
> I think it's intentional for the test, please check again @NingLin-P

`previous log mismatch` and `previous log non-exist` is about comparing the log entries in the `MsgAppend` message and the log entries in the follower's storage, which is done by `LogTerm` and `Index`. But `Term` is the leader's term when sending this message and shouldn't be less than the term of log entries (namely `LogTerm`) that it already has.

2021-11-29 05:54 UTC, Connor1996 approved these changes

2021-11-29 05:54 UTC, merged